//던전 옵션
export const dungeonOptions = [
    { value: "present_garulea_garulea", label: "현대 가를레아 대륙" },
    { value: "ancient_garulea_garulea", label: "고대 가를레아 대륙"},
    { value: "future_garulea_garulea", label: "미래 가를레아 대륙"},
    { value: "shadow_dimension", label: "명협계"},
    { value: "present_miglania_atelier", label: "망향의 아틀리에 - 묘소" },
    { value: "present_miglania_atelier_2", label: "망향의 아틀리에 - 순례" },
    { value: "ancient_zerberiya_crystal", label: "고대 제르베리야 결정" },
    { value: "ancient_zerberiya_shadow", label: "고대 제르베리야 그림자" },
    { value: "ancient_zerberiya_thunder", label: "고대 제르베리야 번개"},
    { value: "ancient_zerberiya_eden", label: "실락의 도시"},
    { value: "ancient_miglania_swamp", label: "식인 늪" },
    { value: "ancient_miglania_dragonpalace", label: "용궁성"},
    { value: "ancient_miglania_nadara", label: "나다라 화산"},
    { value: "ancient_miglania_star", label: "별의 탑"},
    { value: "ancient_miglania_tales", label: "환시가 꿈꾸는 이야기"},
    { value: "ancient_miglania_time", label: "시간의 탑"},
    { value: "etc_exp", label: "봉역 어렴풋한 시각의 틈새"},
    { value: "etc_git", label: "봉역 덧없는 시각의 틈새"},
    { value: "future_miglania_corridor", label: "시층회랑"},
    { value: "future_miglania_garden", label: "공중정원"},
    { value: "future_miglania_industry", label: "공업도시 폐허"},
    { value: "future_miglania_kms", label: "구 KMS 본사"},
    { value: "future_miglania_mayu", label: "마유의 꿈 의식"},
    { value: "future_miglania_saki", label: "사키의 꿈 의식"},
    { value: "future_miglania_ship", label: "차원전함"},
    { value: "future_miglania_toto", label: "토토 드림랜드"},
    { value: "future_miglania_zeno", label: "제노 도메인"},
    { value: "present_miglania_beastcastle", label: "마수성"},
    { value: "present_miglania_damak", label: "뱀의 간 다마크"},
    { value: "present_miglania_dogma", label: "도그마의 탑"},
    { value: "present_miglania_firecastle", label: "불타는 마수성"},
    { value: "present_miglania_labyrinth", label: "미글랜스 지하미궁"},
    { value: "present_miglania_mementos", label: "메멘토스"},
    { value: "present_miglania_miglance", label: "미글랜스 성"},
    { value: "present_miglania_moon", label: "달그림자 숲"},
    { value: "present_miglania_weird", label: "기묘한 숲"},
    { value: "present_miglania_rucyana", label: "비경 - 루차나 고적"},
    { value: "present_miglania_chrono1", label: "이몽 - 시간의 탑"},
    { value: "future_miglania_machine", label: "상야의 영장기관"}
];